export interface Service {
  id: string
  slug: string
  title: string
  shortDescription: string
  fullDescription: string
  icon: string
  features: string[]
}

export const services: Service[] = [
  {
    id: '1',
    slug: 'pc-repair',
    title: 'PC Repair & Diagnostics',
    shortDescription: 'Fast, reliable computer repair for home and business systems.',
    fullDescription: 'Comprehensive PC repair and diagnostic services for both personal and business computers. We diagnose hardware and software issues quickly and provide cost-effective solutions to get your systems back online.',
    icon: 'Wrench',
    features: [
      'Hardware diagnostics and repair',
      'Component replacement',
      'BIOS and firmware updates',
      'Motherboard repair',
      'Power supply replacement',
      'Thermal management solutions',
      'On-site and remote support available',
    ],
  },
  {
    id: '2',
    slug: 'custom-builds',
    title: 'Custom PC Builds',
    shortDescription: 'Gaming, workstation, and server builds tailored to your needs.',
    fullDescription: 'We build custom PCs optimized for gaming, professional workstations, home servers, or business applications. Each system is configured, tested, and optimized for performance before delivery.',
    icon: 'Cpu',
    features: [
      'Gaming PC builds',
      'Professional workstations',
      'Server configurations',
      'Component selection guidance',
      'System optimization',
      'Quality assurance testing',
      'Custom cooling solutions',
    ],
  },
  {
    id: '3',
    slug: 'printer-support',
    title: 'Printer Support & Setup',
    shortDescription: 'Professional printer setup, maintenance, and troubleshooting.',
    fullDescription: 'From initial setup and installation to ongoing maintenance and troubleshooting, we keep your printers running smoothly. We support inkjet, laser, and network printers.',
    icon: 'Printer',
    features: [
      'Printer installation and setup',
      'Driver installation',
      'Network printer configuration',
      'Maintenance and cleaning',
      'Toner and cartridge management',
      'Troubleshooting and repair',
      'Multi-printer environment support',
    ],
  },
  {
    id: '4',
    slug: 'networking',
    title: 'Wireless Networking',
    shortDescription: 'Home and business networking solutions for reliable connectivity.',
    fullDescription: 'Secure, fast, and reliable wireless networks for homes and businesses. We design, install, and maintain networks tailored to your specific needs and coverage requirements.',
    icon: 'Wifi',
    features: [
      'WiFi network design',
      'Router installation and configuration',
      'Network security setup',
      'Range extension solutions',
      'Home automation integration',
      'Business network optimization',
      'Performance monitoring',
    ],
  },
  {
    id: '5',
    slug: 'service-agreements',
    title: 'Service Agreements',
    shortDescription: 'Ongoing support plans for residential and business clients.',
    fullDescription: 'Flexible service agreements designed to keep your systems maintained and supported. Choose from maintenance plans, emergency response, or comprehensive managed services.',
    icon: 'Shield',
    features: [
      'Preventive maintenance plans',
      'Priority emergency support',
      'Regular system updates',
      'Hardware monitoring',
      'Performance optimization',
      'Customizable coverage options',
      'Cost-effective bundled services',
    ],
  },
  {
    id: '6',
    slug: 'fiber-internet',
    title: 'High-Speed Fiber Internet',
    shortDescription: 'Blazing-fast fiber internet services for home and business.',
    fullDescription: 'We provide high-speed fiber internet service that transforms your online experience. Experience gigabit speeds, low latency, and reliability for streaming, gaming, and business needs.',
    icon: 'Zap',
    features: [
      'Gigabit fiber connections',
      'Low-latency performance',
      'Reliable uptime',
      'Professional installation',
      'Residential and business plans',
      'Static IP options',
      ' 24/7 technical support',
    ],
  },
  {
    id: '7',
    slug: 'virus-removal',
    title: 'Virus Removal & Malware Protection',
    shortDescription: 'Comprehensive virus and malware removal and prevention.',
    fullDescription: 'Keep your systems secure with our virus removal and malware protection services. We remove existing threats and implement protective measures to prevent future infections.',
    icon: 'AlertTriangle',
    features: [
      'Virus and malware scanning',
      'Threat removal and cleanup',
      'Security software installation',
      'Firewall configuration',
      'Safe browsing education',
      'Regular security updates',
      'Ongoing protection monitoring',
    ],
  },
  {
    id: '8',
    slug: 'system-cleanup',
    title: 'System Cleanup & Performance',
    shortDescription: 'Optimize your system for speed and reliable performance.',
    fullDescription: 'Over time, systems accumulate clutter that slows performance. We clean unnecessary files, optimize settings, and fine-tune your hardware for peak efficiency.',
    icon: 'Zap',
    features: [
      'Temporary file removal',
      'Registry cleanup',
      'Startup program optimization',
      'Disk defragmentation',
      'Memory optimization',
      'Cache clearing',
      'Performance benchmarking',
    ],
  },
  {
    id: '9',
    slug: 'data-backup',
    title: 'Data Backup & Recovery',
    shortDescription: 'Secure your data with professional backup and recovery services.',
    fullDescription: 'Protect your valuable data with automated backup solutions and comprehensive recovery services. We ensure your files are safe, accessible, and recoverable when you need them.',
    icon: 'Database',
    features: [
      'Cloud and local backup setup',
      'Automated backup scheduling',
      'Encrypted data storage',
      'File recovery services',
      'Disaster recovery planning',
      'Version history management',
      'Multiple backup locations',
    ],
  },
]
